name: Run Script Every 3 Hours

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:       # (optional) manual run button

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run my script
        run: python tests/send_mail.py
