name: Run Script Every 3 Hours

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:       # (optional) manual run button

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Debug info
        run: echo "Running email script at $(date)"
      - name: Run my script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python3 tests/send_mail.py
